### ISSUE TITLE
Block icons don't like Brave Browser

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#142]
From this [tweet](https://twitter.com/qnjctckzz8/status/1286343951046369290/photo/1):

![image](https://user-images.githubusercontent.com/10330103/88356596-0a47a280-cd86-11ea-86ba-044d5b7559ea.png)

**Comment by qnjctckzz8** [comment]
TBH I was't quite sure what you meant on twitter and since the thread was about something else I didn't say anything.
But I think that's just a unfortunate screenshot, because the refresh-rate of the blocks was so high at that moment.
When blocks aren't flying in exactly at the moment I take the screenshot it looks like this:

![Blocks](https://user-images.githubusercontent.com/68706691/88461483-2e99a100-cea4-11ea-8eb5-8f10b7095f18.png)

And from what I've now seen on screenshots of other people, thats what it should look like, no?
Just so that you don't search for a bug that isn't there 😄

**Comment by mayankchhabra** [comment]
Wow, lol. Thanks a ton, man! You really saved me from a lot of pain.
