### ISSUE TITLE
Allow access to the dashboard if Bitcoin Core is rewinding blocks

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dashboard#151]
Currently, the dashboard cannot be accessed if `bitcoind` is rewinding blocks. However, since during the IBD, the backend for `lnd` is `neutrino`, we can actually allow access to the dashboard. 

Maybe even show the progress of rewind if we can get that info from `bitcoind`.

**Comment by nolim1t** [comment]
thats possible.. but RPC is not accessible I think. 

Would need to do the following:

- [ ] Modify the middleware lnd/status endpoint to not check bitcoind
- [ ] Change dashboard logic so that if bitcoind is not available it should still log in but give some visual indicator that bitcoind is not fully initialized (maybe tie it in with the neutrino indicator logic #129 )

**Comment by mayankchhabra** [comment]
>  but RPC is not accessible I think

Um, that's how `umbrel-middleware`[ interacts the `bitcoind`](https://github.com/getumbrel/umbrel-middleware/blob/master/services/bitcoind.js), or am I missing something?

**Comment by nolim1t** [comment]
If rewinding blocks or rescanning rpc is not available

**Comment by mayankchhabra** [comment]
Ah, got you... Perhaps we can infer it from `bitcoind`'s logs somehow. If I'm not wrong, the RPC does return an error that says `bitcoind` is rewinding blocks, right? And if so, we could use that?
