### ISSUE TITLE
Keysend transactions doesn't appear in list on Lightning Network panel

### ISSUE THREAD

**Issue by klicha** [getumbrel/umbrel-dashboard#299]
They are correctly added to lightning wallet balance but they doesn't appear in transactions list. They are correctly displayed an payment channels balances as well.

**Comment by jamescridland** [comment]
This appears still an issue today (24 Aug).

RTL shows the keysend transaction, but the transaction is nowhere within Umbrel's UX.

**Comment by brianoflondon** [comment]
Ride the Lightning will display just the amount.

Look in Transactions -> Invoices.

Unfortunately no other details are decoded yet.

**Comment by jamescridland** [comment]
That's true; but within the Umbrel interface, not even that is displayed!

**Comment by brianoflondon** [comment]
Absolutely. I wish I had the spare capacity to do something nice and pretty with my code for decoding Podcasting 2.0 data from Umbrel but I really don't.

IF anyone out there does want to write a pretty App to do this, and wants to collab with me I can probably open source the backend python that does the decoding.

I'm not spending any more time on this though because I know others are doing something.

**Comment by tlindi** [comment]
Is this really still open? I'm giving workshop of Umbrel on few days and I'd like not to confuse new noders with RTL.

**Comment by klicha** [comment]
Yes, it is. You can only see keysend payments in RTL, Thunderhub ... not in Lightning Node app

**Comment by nmfretz** [comment]
Closed by https://github.com/getumbrel/umbrel-lightning/commit/f3f1ab497da9c2c632a4e82465135e5fa63a96cb
